# Generated by Django 5.2.3 on 2025-06-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
