# Generated by Django 5.2.3 on 2025-06-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.CharField(blank=True, help_text='Основная специализация мастера', max_length=200, verbose_name='Специализация'),
        ),
    ]
